package com.iskeru.javapix.pix;

import java.math.BigDecimal;

/**
 * Parser and validator for PIX "copia e cola" payloads generated by this library.
 * <p>
 * It focuses only on the fields currently supported by {@link PixCopyAndPaste} and will ignore
 * unknown or new fields. The parser also validates the CRC-16 when present.
 * </p>
 */
public final class PixCopyAndPasteParser {
    private PixCopyAndPasteParser() {}

    /**
     * Parses a PIX Copy and Paste payload string, validating CRC if present,
     * and extracting the supported fields into {@link PixTarget} and {@link PixTransaction}.
     *
     * @param payload PIX payload text
     * @return parsed data
     * @throws IllegalArgumentException if the payload is malformed or CRC is invalid
     */
    public static PixCopyAndPaste parse(String payload) {
        if (payload == null || payload.isEmpty()) {
            throw new IllegalArgumentException("Empty PIX payload");
        }

        // If CRC field (63) is present, validate it
        validateCrcIfPresent(payload);

        String nome = null;
        String pais = null;
        String cidade = null;
        String chavePix = null;
        BigDecimal amount = null;
        String currency = null;
        String txid = null;

        int i = 0;
        while (i < payload.length()) {
            if (i + 4 > payload.length()) break; // avoid OOB
            String id = payload.substring(i, i + 2);
            int len = parseLen(payload, i + 2);
            int vStart = i + 4;
            int vEnd = vStart + len;
            if (vEnd > payload.length()) {
                throw new IllegalArgumentException("Malformed TLV length for field " + id);
            }
            String value = payload.substring(vStart, vEnd);

            if (id.equals(PixCopyAndPaste.Fields.MERCHANT_ACCOUNT_INFO)) {
                // Nested TLV: GUI(00) and Key(01)
                chavePix = extractPixKey(value);
            } else if (id.equals(PixCopyAndPaste.Fields.TRANSACTION_CURRENCY)) {
                if ("986".equals(value)) {
                    currency = "BRL";
                } else {
                    currency = value; // keep numeric if unknown
                }
            } else if (id.equals(PixCopyAndPaste.Fields.TRANSACTION_VALUE)) {
                try {
                    amount = new BigDecimal(value);
                } catch (NumberFormatException e) {
                    throw new IllegalArgumentException("Invalid amount: " + value);
                }
            } else if (id.equals(PixCopyAndPaste.Fields.MERCHANT_COUNTRY)) {
                pais = value;
            } else if (id.equals(PixCopyAndPaste.Fields.MERCHANT_NAME)) {
                nome = value;
            } else if (id.equals(PixCopyAndPaste.Fields.MERCHANT_CITY)) {
                cidade = value;
            } else if (id.equals(PixCopyAndPaste.Fields.ADDITIONAL_DATA)) {
                // Nested TLV for TXID (05)
                txid = extractTxId(value);
            } else if (id.equals(PixCopyAndPaste.Fields.CRC16)) {
                // already validated above; nothing to do
            } else {
                // ignore unsupported fields
            }

            i = vEnd;
        }

        if (chavePix == null || chavePix.isEmpty()) {
            throw new IllegalArgumentException("Missing PIX key (26.01)");
        }
        if (amount == null) {
            throw new IllegalArgumentException("Missing amount (54)");
        }

        PixTarget target = PixTarget.builder()
                .chavePix(chavePix)
                .nome(nome)
                .pais(pais)
                .cidade(cidade)
                .build();
        PixTransaction tx = PixTransaction.builder()
                .valorTransacao(amount)
                .currency(currency)
                .idTransacao(txid)
                .build();

        return PixCopyAndPaste.builder()
                .to(target)
                .transfer(tx)
                .build();
    }

    /**
     * Validates CRC-16/CCITT if the payload ends with field 63 (CRC). If present and invalid, throws.
     * @param payload the payload
     */
    public static void validateCrcIfPresent(String payload) {
        int i = 0;
        while (i + 4 <= payload.length()) {
            String id = payload.substring(i, i + 2);
            int len = parseLen(payload, i + 2);
            int vStart = i + 4;
            int vEnd = vStart + len;
            if (vEnd > payload.length()) {
                throw new IllegalArgumentException("Malformed TLV length while scanning CRC");
            }

            if (id.equals(PixCopyAndPaste.Fields.CRC16)) {
                if (len != 4) {
                    throw new IllegalArgumentException("CRC length must be 4, got " + len);
                }
                String providedCrc = payload.substring(vStart, vEnd).toUpperCase();
                String base = payload.substring(0, i) + PixCopyAndPaste.Fields.CRC16 + "04";
                String expected = PixCRC16.crcChecksum(base).toUpperCase();
                if (!providedCrc.equals(expected)) {
                    throw new IllegalArgumentException("Invalid CRC: expected " + expected + " but got " + providedCrc);
                }
                return; // validated
            }
            i = vEnd;
        }
        // no CRC present: do nothing
    }

    private static int parseLen(String s, int offset) {
        if (offset + 2 > s.length()) throw new IllegalArgumentException("Malformed TLV length");
        String lenStr = s.substring(offset, offset + 2);
        try {
            return Integer.parseInt(lenStr);
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("Invalid TLV length: " + lenStr);
        }
    }

    private static String extractPixKey(String nested) {
        String gui = null;
        String key = null;
        int i = 0;
        while (i + 4 <= nested.length()) {
            String id = nested.substring(i, i + 2);
            int len = parseLen(nested, i + 2);
            int vStart = i + 4;
            int vEnd = vStart + len;
            if (vEnd > nested.length()) break;
            String value = nested.substring(vStart, vEnd);
            if (PixCopyAndPaste.Fields.MERCHANT_ACCOUNT_INFO_GUI.equals(id)) {
                gui = value;
            } else if (PixCopyAndPaste.Fields.MERCHANT_ACCOUNT_INFO_PIX_KEY.equals(id)) {
                key = value;
            }
            i = vEnd;
        }
        // Validate GUI when present
        if (gui != null && !PixCopyAndPaste.Fields.MERCHANT_ACCOUNT_INFO_GUI_VALUE.equals(gui)) {
            // Some banks may use lowercase, support it as well
            if (!"br.gov.bcb.pix".equals(gui)) {
                throw new IllegalArgumentException("Unexpected GUI in merchant account info: " + gui);
            }
        }
        return key;
    }

    private static String extractTxId(String nested) {
        String txid = null;
        int i = 0;
        while (i + 4 <= nested.length()) {
            String id = nested.substring(i, i + 2);
            int len = parseLen(nested, i + 2);
            int vStart = i + 4;
            int vEnd = vStart + len;
            if (vEnd > nested.length()) break;
            String value = nested.substring(vStart, vEnd);
            if (PixCopyAndPaste.Fields.ADDITIONAL_DATA_TXID.equals(id)) {
                txid = value;
            }
            i = vEnd;
        }
        return txid;
    }
}
